/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ecoactivistas.config.vistas;

import com.mycompany.ecoactivistas.controller.ActivistaController;
import com.mycompany.ecoactivistas.controller.ProblemaActivistaController;
import com.mycompany.ecoactivistas.controller.ProblemaController;
import com.mycompany.ecoactivistas.model.Problema;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Afgord
 */
public class frmProblemasActivistas extends javax.swing.JPanel {

    int idProblema;
    private Problema problema;
    private ProblemaActivistaController paController;
    private ActivistaController activistaController;
    private ProblemaController problemaController;

    /**
     * Creates new form frmProblemasActivistas
     */
    public frmProblemasActivistas() {
        initComponents();
        paController = new ProblemaActivistaController();
        activistaController = new ActivistaController();
        problemaController = new ProblemaController();
        cargarDisponibles();
        cargarAsignados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAsignar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnProblemas = new javax.swing.JButton();
        txtProblema = new javax.swing.JTextField();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisponibles = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAsignados = new javax.swing.JTable();

        setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("ASIGNAR ACTIVISTA A PROBLEMA");

        btnAsignar.setText("ASIGNAR");
        btnAsignar.addActionListener(this::btnAsignarActionPerformed);

        btnQuitar.setText("QUITAR");
        btnQuitar.addActionListener(this::btnQuitarActionPerformed);

        jLabel2.setText("PROBLEMA");

        jLabel3.setText("Activistas disponibles");

        jLabel4.setText("Activistas asignados");

        btnProblemas.setText("BUSCAR");
        btnProblemas.addActionListener(this::btnProblemasActionPerformed);

        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setResizeWeight(0.5);
        jSplitPane1.setOneTouchExpandable(true);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 402));

        tblDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDisponibles);

        jSplitPane1.setLeftComponent(jScrollPane1);

        tblAsignados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblAsignados);

        jSplitPane1.setRightComponent(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProblemas)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(252, 252, 252)
                                .addComponent(jLabel4)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jSplitPane1)
                .addGap(453, 453, 453))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btnAsignar)
                .addGap(280, 280, 280)
                .addComponent(btnQuitar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnProblemas)
                    .addComponent(txtProblema))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAsignar)
                    .addComponent(btnQuitar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        // TODO add your handling code here:
        asignar();
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        // TODO add your handling code here:
        quitar();
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnProblemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProblemasActionPerformed
        // TODO add your handling code here:
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        DlgBuscarProblemas dlg = new DlgBuscarProblemas(frame, true); // modal
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true); // esto bloquea hasta cerrar el diálogo

        // Después de cerrar, obtener el problema seleccionado
        Integer idSeleccionado = dlg.getProblemaSeleccionado();
        if (idSeleccionado != null) {
            this.problema = problemaController.obtenerProblema(idSeleccionado);
            this.idProblema = idSeleccionado;
            txtProblema.setText(this.problema.getDescripcion());

            cargarDisponibles();
            cargarAsignados();

        }
    }//GEN-LAST:event_btnProblemasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnProblemas;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable tblAsignados;
    private javax.swing.JTable tblDisponibles;
    private javax.swing.JTextField txtProblema;
    // End of variables declaration//GEN-END:variables
    private void cargarDisponibles() {
        tblDisponibles.setModel(paController.obtenerTablaActivistasDisponibles(idProblema));
    }

    private void cargarAsignados() {
        tblAsignados.setModel(paController.obtenerTablaActivistasAsignados(idProblema));
    }

    private void asignar() {

        int fila = tblDisponibles.getSelectedRow();

        if (fila < 0) {

            JOptionPane.showMessageDialog(this, "Seleccione un activista");
            return;
        }

        int idActivista = (int) tblDisponibles.getValueAt(fila, 0);
        boolean exito = paController.asignarActivista(idProblema, idActivista);

        if (exito) {

            JOptionPane.showMessageDialog(this, "Se asignó un activista al problema correctamente.");
            cargarDisponibles();
            cargarAsignados();

        } else {

            JOptionPane.showMessageDialog(this, "Error al asignar");

        }
    }

    private void quitar() {

        int fila = tblAsignados.getSelectedRow();

        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un activista");
            return;
        }

        int idActivista = (int) tblAsignados.getValueAt(fila, 0);
        boolean exito = paController.eliminarAsignacion(idProblema, idActivista);

        if (exito) {

            JOptionPane.showMessageDialog(this, "Se eliminó un activista al problema correctamente.");
            cargarDisponibles();
            cargarAsignados();

        } else {

            JOptionPane.showMessageDialog(this, "Error al eliminar");

        }
    }

}
